sudo: required

notifications:
  email: false

language: python

before_install:
  # C++17
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-6 g++-6 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

python:
  - "3.6"
  
cache: pip
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  
# command to run tests
script:
  - pip install . --verbose
  - python Pyfhel/test.py
